apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hellonode.fullname" . }}
  labels:
    app: {{ template "hellonode.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  myconfig.txt: |
    This is a sample text file.
    It is not sensitive, so is handled by ConfigMap instead of Secrets.
