apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "hellonode.fullname" . }}
  labels:
    app: {{ template "hellonode.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "hellonode.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "hellonode.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: myconfig
              readOnly: true
              mountPath: /var/config
            - name: mysecret
              readOnly: true
              mountPath: /var/secret
      volumes:
        - name: myconfig
          configMap:
            name: {{ template "hellonode.fullname" . }}
        - name: mysecret
          secret:
            secretName: {{ template "hellonode.fullname" . }}
