apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hellonode
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: hellonode
              servicePort: 8080
