apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hellonode.fullname" . }}
  labels:
    app: {{ template "hellonode.name" . }}
    chart: {{ template "hellonode.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mysecret.txt: {{ .Files.Get .Values.mySecretPath | b64enc }}
