---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hellonode
  namespace: hellonode
data:
  foo.txt: |
    Hello, world!
    This is a sample text file.
---
apiVersion: v1
kind: Service
metadata:
  name: hellonode
  namespace: hellonode
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: nodejs
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hellonode
  namespace: hellonode
spec:
  replicas: 1
  template:
    metadata:
      name: hellonode
      labels:
        app: nodejs
    spec:
      volumes:
        - name: myconfig
          configMap:
            name: hellonode
        - name: mysecret
          secret:
            secretName: hellonode
      containers:
        - name: hellonode
          image: hellonode:v1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: myconfig
              readOnly: true
              mountPath: /var/config
            - name: mysecret
              readOnly: true
              mountPath: /var/secret
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hellonode
  namespace: hellonode
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: hellonode
              servicePort: 8080
